version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 975050048882.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ijse_ai_test:green .
      - echo Tagging the previous green image as blue...
      - docker tag ijse_ai_test:green 975050048882.dkr.ecr.ap-southeast-1.amazonaws.com/ijse_ai_test:blue
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 975050048882.dkr.ecr.ap-southeast-1.amazonaws.com/ijse_ai_test:green
      - docker push 975050048882.dkr.ecr.ap-southeast-1.amazonaws.com/ijse_ai_test:blue
      - echo Writing image definitions file...
      - printf '[{"name":"mywebsite","imageUri":"%s"}]' 975050048882.dkr.ecr.ap-southeast-1.amazonaws.com/ijse_ai_test:blue > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
